server:
  port: 8080

logging:
  level:
    org.atmosphere: warn

spring:
  mustache:
    check-template-location: false

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,com.example.application
